# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Pro\Py\TCPro\1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2688, 1738)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(2580, 8, 101, 61))
        self.pushButton.setText("")
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(2481, 8, 101, 61))
        self.pushButton_2.setText("")
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(2382, 8, 101, 61))
        self.pushButton_3.setText("")
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.line = QtWidgets.QFrame(Form)
        self.line.setEnabled(True)
        self.line.setGeometry(QtCore.QRect(7, 65, 2674, 10))
        self.line.setSizeIncrement(QtCore.QSize(20, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.columnView = QtWidgets.QColumnView(Form)
        self.columnView.setGeometry(QtCore.QRect(672, 8, 1712, 57))
        self.columnView.setObjectName("columnView")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(7, 8, 81, 58))
        self.pushButton_4.setText("")
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(87, 8, 101, 57))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(188, 8, 101, 57))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(289, 8, 101, 57))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setGeometry(QtCore.QRect(390, 8, 141, 57))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(Form)
        self.comboBox_5.setGeometry(QtCore.QRect(531, 8, 141, 57))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.columnView_2 = QtWidgets.QColumnView(Form)
        self.columnView_2.setGeometry(QtCore.QRect(1570, 69, 1111, 131))
        self.columnView_2.setObjectName("columnView_2")
        self.comboBox_6 = QtWidgets.QComboBox(Form)
        self.comboBox_6.setGeometry(QtCore.QRect(1050, 69, 521, 131))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(Form)
        self.comboBox_7.setGeometry(QtCore.QRect(529, 69, 521, 131))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(Form)
        self.comboBox_8.setGeometry(QtCore.QRect(8, 69, 521, 131))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 116, 40, 40))
        self.pushButton_5.setText("")
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(560, 117, 40, 40))
        self.pushButton_6.setText("")
        self.pushButton_6.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(1080, 117, 40, 40))
        self.pushButton_7.setText("")
        self.pushButton_7.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_7.setAutoDefault(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(7, 200, 262, 81))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(267, 200, 263, 81))
        self.pushButton_9.setObjectName("pushButton_9")
        self.columnView_3 = QtWidgets.QColumnView(Form)
        self.columnView_3.setGeometry(QtCore.QRect(530, 200, 2151, 1531))
        self.columnView_3.setObjectName("columnView_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(1380, 330, 541, 121))
        self.label.setObjectName("label")
        self.columnView_4 = QtWidgets.QColumnView(Form)
        self.columnView_4.setGeometry(QtCore.QRect(9, 1220, 521, 511))
        self.columnView_4.setObjectName("columnView_4")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(151, 1257, 351, 71))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(41, 1257, 91, 71))
        self.pushButton_10.setText("")
        self.pushButton_10.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_10.setAutoDefault(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.columnView_5 = QtWidgets.QColumnView(Form)
        self.columnView_5.setGeometry(QtCore.QRect(43, 1350, 458, 291))
        self.columnView_5.setObjectName("columnView_5")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(42, 1652, 458, 57))
        self.pushButton_11.setStyleSheet("font: 9pt \"Arial\";")
        self.pushButton_11.setObjectName("pushButton_11")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.close)
        self.pushButton_3.clicked.connect(Form.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "File"))
        self.comboBox_2.setItemText(0, _translate("Form", "Edit"))
        self.comboBox_3.setItemText(0, _translate("Form", "View"))
        self.comboBox_4.setItemText(0, _translate("Form", "Repose"))
        self.comboBox_5.setItemText(0, _translate("Form", "Branch"))
        self.comboBox_6.setItemText(0, _translate("Form", "        Fetch orign"))
        self.comboBox_7.setItemText(0, _translate("Form", "        Master"))
        self.comboBox_8.setItemText(0, _translate("Form", "        ThePro"))
        self.pushButton_8.setText(_translate("Form", "Changes"))
        self.pushButton_9.setText(_translate("Form", "History"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\">暂无新消息</p></body></html>"))
        self.pushButton_11.setText(_translate("Form", "Commit Ehciy"))
        file = QtCore.QFile('css.css')
        file.open(QtCore.QFile.ReadOnly)
        styleSheet = file.readAll()
        styleSheet = str(styleSheet, encoding='utf8')
        self.setStyleSheet(styleSheet)

